# 제네레이터

- 코드 블록의 실행을 중지하고 필요한 시점에 재개할수 있는 특수한 함수

제네레이터 vs 일반함수

- 일반함수는 함수 호출시 제어권이 함수에게 넘어가지만 제네레이터는 함수 실행을 호출자가 제어할수 있음 (yield)

- 제네레이터는 함수 호출자와 함수의 상태를 주고 받을 수 있음 

- 제네레이터 함수를 호출하면 값을 반환하지 않고 제네레이터 객체를 반환 (이터러블이면서 이터레이터)

## 제네레이터 함수 정의

- 제네레이터 함수는 function* 키워드로 선언 
- `function* genFun() { yield 1; } `
- (*) 위치는 function 키워드와 함수 이름 사이 어디에다 써도 무관 (위 예제와 같이 function 키워드 바로 붙히는게 일반적)  
- 화살표 함수로는 정의할수 없음
- new 연산자와 함께 생성자 함수로써 호출할수 없음

```javascript
function* genFunc() {
  try {
    yield 1;
    yield 2;
    yield 3;
  } catch (e) {
    console.error(e);
  }
}

const generator = genFunc(); // generator에는 제네레이터 객체가 담기는데 이는 next, return, throw 같은 메서드를 가짐

console.log(generator.next()) // {value: 1, done: false}
console.log(generator.next()) // {value: 2, done: false}
// 여기서 또 generator.next() 하면 {value: 3, done : false }
// 한번더 generator.next()를 하면 {value: undefined, done: true} 이런식으로 완료가 되지만 return 을 사용해 완료값과 done 상태를 바꿀수있음.
console.log(generator.return('end here')) // {value: 'end here', done: true}
// console.log(generator.throw('Error)') - {value: undefined, done: true} 도 가능

```

제네레이터 함수의 next 메서드에 인수를 전달할수 있는데 이는 yield 표현식을 할당받는 변수에 할당됨.
** 평가 결과가 할당되지 않음 

```javascript
function* genFunc() {
  const a = yield 1;
  const b = yield a + 10;
  const c = yield a + b;
}
let g = genFunc()
console.log(g.next()) // 제네레이터 시작  {value: 1, done: false }
console.log(g.next(1)) // a = 1 b = 11 {value: 11, done: false }
console.log(g.next(2)) //  a = 1 , b = 2{value: 3, done: false }

```

# async/await

제네레이터를 사용해 비동기 처리를 할수 있지만 가독성 좋게 비동기 처리를 동기 처리처럼 동작하도록 async/await가 es7에 도입

```javascript
async function fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1'
  // 후속 처리 메서드 없이 처리 결과를 반환
  //  async 함수 내부에서 await를 사용해야함
  const response = await fetch(url);
  const todo = await response.json();
  console.log(todo)
}
```

## 에러처리

async를 사용하지 않으면 비동기 함수의 콜백 함수를 호출한 것은 비동기 함수가 아니기에 try... catch를 사용할수 없으나 async/await 에서는 프로미스를 반환하는 비동기 함수는 명시적으로 호출할수 있기에 호출자가 명확함.

```javascript
const tryFetch = async () => {
  try {
    /* fetch 로직 */
  } catch (err) {
    console.error(err)
  }
}
```

또는 후속 처리 메서드를 사용할수 있음

```javascript
const tryFetch = async () => {
  try {
    /* fetch 로직 */
  } catch (err) {
    console.error(err)
  }
}
tryFetch()
.then(console.log())
.catch(console.error(err))
```